//! Student agent — model instance with LoRA specialization.
//!
//! Spec §6.1.1: Each student is a clone of the shared base model with
//! a unique LoRA adapter. Students attempt to solve problems by generating
//! byte sequences (proof attempts) autoregressively.
//!
//! Spec §6.1.2: Students are isolated — they share the base weights
//! (read-only) but each has independent LoRA state and SSM hidden state.
//!
//! # Novel technique: NPSI (Noise-Perturbed Specialization Injection)
//!
//! Before each problem attempt, NPSI injects Gaussian noise into the
//! student's LoRA B matrix, scaled by:
//!   noise_scale = base_noise * (1.0 + 0.1 * curriculum_level)
//!
//! This creates exploration diversity in sequential execution. The noise
//! magnitude increases with curriculum level because harder problems
//! benefit from wider search. The A matrix is left clean (zero-init)
//! so the noise only affects the output projection, not the input
//! compression — this preserves learned feature detection while
//! randomising the solution strategy.

use crate::teacher::Problem;
use sophon_core::rng::Rng;

// ---------------------------------------------------------------------------
// StudentConfig
// ---------------------------------------------------------------------------

/// Configuration for student agents.
#[derive(Debug, Clone)]
pub struct StudentConfig {
    /// Base noise scale for NPSI (default 0.01).
    pub base_noise: f32,
    /// Maximum tokens to generate per solution attempt.
    pub max_generation_tokens: usize,
    /// Temperature for sampling (0.0 = greedy, >0 = stochastic).
    pub temperature: f32,
    /// LoRA alpha for student adapters.
    pub lora_alpha: f32,
}

impl Default for StudentConfig {
    fn default() -> Self {
        Self {
            base_noise: 0.01,
            max_generation_tokens: 512,
            temperature: 0.8,
            lora_alpha: 1.0,
        }
    }
}

// ---------------------------------------------------------------------------
// SolutionAttempt
// ---------------------------------------------------------------------------

/// A student's attempt at solving a problem.
#[derive(Debug, Clone)]
pub struct SolutionAttempt {
    /// Which student produced this.
    pub student_id: u32,
    /// Problem ID this attempts to solve.
    pub problem_id: u64,
    /// Generated byte sequence (the proof attempt).
    pub generated_bytes: Vec<u8>,
    /// Generated text (UTF-8 interpretation of bytes).
    pub generated_text: String,
    /// Tactics extracted from the generated text.
    pub tactics_used: Vec<String>,
    /// Per-token log probabilities (for scoring).
    pub log_probs: Vec<f32>,
    /// Mean negative log probability (lower = more confident).
    pub mean_nll: f32,
    /// Whether this was verified by the triviality filter.
    pub passed_triviality: bool,
    /// Whether this was verified by Lean (if available).
    pub lean_verified: bool,
}

// ---------------------------------------------------------------------------
// Student
// ---------------------------------------------------------------------------

/// A student agent in the swarm classroom.
///
/// Each student wraps a reference to the shared model configuration
/// but maintains its own LoRA state. Since we run sequentially on
/// current hardware, the "student" is really a lightweight wrapper
/// that perturbs the shared model's LoRA adapters.
pub struct Student {
    /// Unique student ID.
    pub id: u32,
    /// Configuration.
    pub config: StudentConfig,
    /// Student-specific RNG.
    rng: Rng,
    /// Total problems attempted by this student.
    pub problems_attempted: u32,
    /// Total problems solved by this student.
    pub problems_solved: u32,
    /// LoRA B perturbation vectors (flat, one per block).
    /// These are added to the shared model's LoRA B matrices before attempt.
    lora_perturbations: Vec<Vec<f32>>,
}

impl Student {
    /// Create a new student with a unique seed.
    pub fn new(id: u32, config: StudentConfig, seed: u64) -> Self {
        Self {
            id,
            config,
            rng: Rng::new(seed),
            problems_attempted: 0,
            problems_solved: 0,
            lora_perturbations: Vec::new(),
        }
    }

    /// Generate NPSI noise for this student given the current curriculum level.
    ///
    /// Returns a vector of perturbation vectors, one per LoRA adapter.
    pub fn generate_noise(
        &mut self,
        n_adapters: usize,
        adapter_b_sizes: &[usize],
        level: u32,
    ) -> Vec<Vec<f32>> {
        let noise_scale = self.config.base_noise * (1.0 + 0.1 * level as f32);
        let mut perturbations = Vec::with_capacity(n_adapters);

        for &size in adapter_b_sizes {
            let mut noise = vec![0.0f32; size];
            self.rng.fill_normal(&mut noise, 0.0, noise_scale);
            perturbations.push(noise);
        }

        self.lora_perturbations = perturbations.clone();
        perturbations
    }

    /// Get the stored perturbations.
    pub fn perturbations(&self) -> &[Vec<f32>] {
        &self.lora_perturbations
    }

    /// Attempt to solve a problem.
    ///
    /// This method simulates the student generating a proof attempt.
    /// In the full system, this would run the model autoregressively.
    /// For the scaffold, we accept pre-generated output and score it.
    pub fn attempt_problem(
        &mut self,
        _problem: &Problem,
        generated_bytes: Vec<u8>,
        token_logits: &[Vec<f32>],
        targets: &[u8],
    ) -> SolutionAttempt {
        self.problems_attempted += 1;

        // Compute per-token log probabilities
        let mut log_probs = Vec::with_capacity(token_logits.len());
        for (logits, &target) in token_logits.iter().zip(targets.iter()) {
            let lp = compute_log_prob(logits, target);
            log_probs.push(lp);
        }

        let mean_nll = if log_probs.is_empty() {
            0.0
        } else {
            -log_probs.iter().sum::<f32>() / log_probs.len() as f32
        };

        let generated_text = String::from_utf8_lossy(&generated_bytes).to_string();
        let tactics_used = extract_tactics(&generated_text);

        SolutionAttempt {
            student_id: self.id,
            problem_id: _problem.id,
            generated_bytes,
            generated_text,
            tactics_used,
            log_probs,
            mean_nll,
            passed_triviality: false, // Set by selection after filter
            lean_verified: false,     // Set by selection after verification
        }
    }

    /// Record that a solution was accepted.
    pub fn record_success(&mut self) {
        self.problems_solved += 1;
    }

    /// Student's overall success rate.
    pub fn success_rate(&self) -> f32 {
        if self.problems_attempted == 0 {
            return 0.0;
        }
        self.problems_solved as f32 / self.problems_attempted as f32
    }
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/// Compute log P(target | logits) using log-softmax.
fn compute_log_prob(logits: &[f32], target: u8) -> f32 {
    if logits.is_empty() {
        return 0.0;
    }

    let max_logit = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let sum_exp: f32 = logits.iter().map(|&l| (l - max_logit).exp()).sum();
    let log_sum_exp = max_logit + sum_exp.ln();

    let target_idx = target as usize;
    if target_idx < logits.len() {
        logits[target_idx] - log_sum_exp
    } else {
        f32::NEG_INFINITY
    }
}

/// Extract tactic names from a Lean-like proof text.
fn extract_tactics(text: &str) -> Vec<String> {
    let known_tactics = [
        "simp",
        "ring",
        "omega",
        "rfl",
        "exact",
        "apply",
        "intro",
        "induction",
        "cases",
        "constructor",
        "left",
        "right",
        "exfalso",
        "contradiction",
        "rw",
        "calc",
        "have",
        "let",
        "show",
        "suffices",
        "by_contra",
        "norm_num",
        "linarith",
        "nlinarith",
        "decide",
        "trivial",
        "assumption",
    ];

    let mut found = Vec::new();
    let lower = text.to_lowercase();
    for &tactic in &known_tactics {
        if lower.contains(tactic) {
            found.push(tactic.to_string());
        }
    }
    found
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::teacher::Problem;

    fn test_problem() -> Problem {
        Problem {
            id: 1,
            statement: "Prove that 0 + n = n".to_string(),
            level: 1,
            tags: vec!["arithmetic".to_string()],
            building_blocks: vec![],
            difficulty: 0.3,
        }
    }

    #[test]
    fn student_creates_with_zero_stats() {
        let s = Student::new(0, StudentConfig::default(), 42);
        assert_eq!(s.id, 0);
        assert_eq!(s.problems_attempted, 0);
        assert_eq!(s.problems_solved, 0);
        assert!((s.success_rate() - 0.0).abs() < 1e-6);
    }

    #[test]
    fn npsi_noise_correct_size() {
        let mut s = Student::new(0, StudentConfig::default(), 42);
        let sizes = vec![100, 200, 50];
        let noise = s.generate_noise(3, &sizes, 1);
        assert_eq!(noise.len(), 3);
        assert_eq!(noise[0].len(), 100);
        assert_eq!(noise[1].len(), 200);
        assert_eq!(noise[2].len(), 50);
    }

    #[test]
    fn npsi_noise_scales_with_level() {
        let config = StudentConfig {
            base_noise: 1.0,
            ..Default::default()
        };
        let mut s1 = Student::new(0, config.clone(), 42);
        let mut s2 = Student::new(1, config, 42);
        let sizes = vec![1000];
        let n1 = s1.generate_noise(1, &sizes, 1);
        let n2 = s2.generate_noise(1, &sizes, 10);

        let var1: f32 = n1[0].iter().map(|v| v * v).sum::<f32>() / 1000.0;
        let var2: f32 = n2[0].iter().map(|v| v * v).sum::<f32>() / 1000.0;
        // Level 10 should have higher variance than level 1
        assert!(var2 > var1, "var2={var2} should be > var1={var1}");
    }

    #[test]
    fn attempt_produces_solution() {
        let mut s = Student::new(0, StudentConfig::default(), 42);
        let problem = test_problem();
        let bytes = b"theorem t : 0 + n = n := by simp".to_vec();
        let logits = vec![vec![0.0f32; 256]; bytes.len()];
        let targets: Vec<u8> = bytes.clone();
        let attempt = s.attempt_problem(&problem, bytes, &logits, &targets);
        assert_eq!(attempt.student_id, 0);
        assert_eq!(attempt.problem_id, 1);
        assert!(!attempt.generated_text.is_empty());
        assert_eq!(s.problems_attempted, 1);
    }

    #[test]
    fn log_prob_correct_for_uniform() {
        // Uniform logits over 256 classes → log(1/256)
        let logits = vec![0.0f32; 256];
        let lp = compute_log_prob(&logits, 42);
        let expected = -(256.0f32).ln();
        assert!((lp - expected).abs() < 1e-4, "lp={lp} expected={expected}");
    }

    #[test]
    fn log_prob_peaked() {
        // Peak at target
        let mut logits = vec![0.0f32; 256];
        logits[10] = 10.0;
        let lp = compute_log_prob(&logits, 10);
        assert!(
            lp > -0.1,
            "peaked logits should give high log prob, got {lp}"
        );
    }

    #[test]
    fn extract_tactics_finds_known() {
        let text = "by simp [add_comm]; ring";
        let tactics = extract_tactics(text);
        assert!(tactics.contains(&"simp".to_string()));
        assert!(tactics.contains(&"ring".to_string()));
    }

    #[test]
    fn success_rate_tracks() {
        let mut s = Student::new(0, StudentConfig::default(), 42);
        s.problems_attempted = 4;
        s.problems_solved = 3;
        assert!((s.success_rate() - 0.75).abs() < 1e-6);
    }
}
